name: hellonius_freshus
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: 7.2.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  equatable: ^2.0.5
  flutter_bloc: ^7.3.3
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/menu.svg
    - lib/assets/icons/error_egg.svg
    - lib/assets/images/risotto.png

  fonts:
    - family: Agrandir
      fonts:
        - asset: lib/assets/fonts/Agrandir-GrandHeavy.otf
        - asset: lib/assets/fonts/Agrandir-GrandLight.otf
        - asset: lib/assets/fonts/Agrandir-Narrow.otf
          weight: 200
        - asset: lib/assets/fonts/Agrandir-Regular.otf
          weight: 500
        - asset: lib/assets/fonts/Agrandir-TextBold.otf
          weight: 900
        - asset: lib/assets/fonts/Agrandir-ThinItalic.otf
          style: italic
        - asset: lib/assets/fonts/Agrandir-Tight.otf
        - asset: lib/assets/fonts/Agrandir-WideBlackItalic.otf
        - asset: lib/assets/fonts/Agrandir-WideLight.otf
