name: hellonius_freshus
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: 7.2.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  equatable: ^2.0.5
  flutter_bloc: ^7.3.3
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/menu.svg
    - lib/assets/icons/error_egg.svg
    - lib/assets/images/coriander.png
    - lib/assets/images/egg.png
    - lib/assets/images/hazelnuts.png
    - lib/assets/images/lime.png
    - lib/assets/images/milk.png
    - lib/assets/images/olive.png
    - lib/assets/images/paleo_diet.png
    - lib/assets/images/peanuts.png
    - lib/assets/images/pescetariar.png
    - lib/assets/images/roasted_edamame.png
    - lib/assets/images/shellfish.png
    - lib/assets/images/soy.png
    - lib/assets/images/treenuts.png
    - lib/assets/images/user.png
    - lib/assets/images/vegan.png
    - lib/assets/images/4.png
    - lib/assets/images/5.png
    - lib/assets/images/allergies/18.png
    - lib/assets/images/allergies/19.png
    - lib/assets/images/allergies/20.png
    - lib/assets/images/allergies/21.png
    - lib/assets/images/27.png
    - lib/assets/images/28.png
    - lib/assets/images/29.png
    - lib/assets/images/30.png
    - lib/assets/images/allergies/31.png
    - lib/assets/images/allergies/32.png
    
    

  fonts:
    - family: Agrandir
      fonts:
        - asset: lib/assets/fonts/Agrandir-Regular.ttf
        - asset: lib/assets/fonts/Agrandir-TextBold.ttf
          weight: 700
